name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.x'

      - name: Install TiddlyWiki
        run: npm install -g tiddlywiki

      - name: Build
        run: tiddlywiki . --output public --build index
        env:
          TIDDLYWIKI_PLUGIN_PATH: plugins

      - name: Set CNAME
        run: echo reinsurance.dev > public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
